
language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-3.9
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0

install:
    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz
    - tar -xvf premake-5.0.0-alpha13-linux.tar.gz 
    - ./premake5 gmake
    - ./premake5 --cc=clang gmake2

script:
    - make -C gmake config=debug verbose=true
    - make -C gmake config=release verbose=true
    - make -C gmake2 config=debug verbose=true
    - make -C gmake2 config=release verbose=true
  
